/*
 * This file is generated by jOOQ.
 */
package ru.itis.agona.model.jooq.schema.tables;


import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.itis.agona.model.jooq.schema.Keys;
import ru.itis.agona.model.jooq.schema.Public;
import ru.itis.agona.model.jooq.schema.tables.records.FoodCategoriesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoodCategories extends TableImpl<FoodCategoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.food_categories</code>
     */
    public static final FoodCategories FOOD_CATEGORIES_ENTITY = new FoodCategories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FoodCategoriesRecord> getRecordType() {
        return FoodCategoriesRecord.class;
    }

    /**
     * The column <code>public.food_categories.id</code>.
     */
    public final TableField<FoodCategoriesRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.food_categories.name</code>.
     */
    public final TableField<FoodCategoriesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50), this, "");

    private FoodCategories(Name alias, Table<FoodCategoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private FoodCategories(Name alias, Table<FoodCategoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.food_categories</code> table reference
     */
    public FoodCategories(String alias) {
        this(DSL.name(alias), FOOD_CATEGORIES_ENTITY);
    }

    /**
     * Create an aliased <code>public.food_categories</code> table reference
     */
    public FoodCategories(Name alias) {
        this(alias, FOOD_CATEGORIES_ENTITY);
    }

    /**
     * Create a <code>public.food_categories</code> table reference
     */
    public FoodCategories() {
        this(DSL.name("food_categories"), null);
    }

    public <O extends Record> FoodCategories(Table<O> child, ForeignKey<O, FoodCategoriesRecord> key) {
        super(child, key, FOOD_CATEGORIES_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FoodCategoriesRecord> getPrimaryKey() {
        return Keys.FOOD_CATEGORIES_PKEY;
    }

    @Override
    public FoodCategories as(String alias) {
        return new FoodCategories(DSL.name(alias), this);
    }

    @Override
    public FoodCategories as(Name alias) {
        return new FoodCategories(alias, this);
    }

    @Override
    public FoodCategories as(Table<?> alias) {
        return new FoodCategories(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FoodCategories rename(String name) {
        return new FoodCategories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FoodCategories rename(Name name) {
        return new FoodCategories(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FoodCategories rename(Table<?> name) {
        return new FoodCategories(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super UUID, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
