/*
 * This file is generated by jOOQ.
 */
package ru.itis.agona.model.jooq.schema.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.itis.agona.model.jooq.schema.tables.EatenFoods;
import ru.itis.agona.model.jooq.schema.tables.pojos.EatenFoodsEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EatenFoodsRecord extends UpdatableRecordImpl<EatenFoodsRecord> implements Record5<UUID, UUID, UUID, Short, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.eaten_foods.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.eaten_foods.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.eaten_foods.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.eaten_foods.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.eaten_foods.food_id</code>.
     */
    public void setFoodId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.eaten_foods.food_id</code>.
     */
    public UUID getFoodId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.eaten_foods.weight</code>.
     */
    public void setWeight(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.eaten_foods.weight</code>.
     */
    public Short getWeight() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.eaten_foods.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.eaten_foods.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, UUID, Short, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, UUID, Short, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return EatenFoods.EATEN_FOODS_ENTITY.ID;
    }

    @Override
    public Field<UUID> field2() {
        return EatenFoods.EATEN_FOODS_ENTITY.USER_ID;
    }

    @Override
    public Field<UUID> field3() {
        return EatenFoods.EATEN_FOODS_ENTITY.FOOD_ID;
    }

    @Override
    public Field<Short> field4() {
        return EatenFoods.EATEN_FOODS_ENTITY.WEIGHT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return EatenFoods.EATEN_FOODS_ENTITY.CREATED_DATE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public UUID component3() {
        return getFoodId();
    }

    @Override
    public Short component4() {
        return getWeight();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public UUID value3() {
        return getFoodId();
    }

    @Override
    public Short value4() {
        return getWeight();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public EatenFoodsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public EatenFoodsRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public EatenFoodsRecord value3(UUID value) {
        setFoodId(value);
        return this;
    }

    @Override
    public EatenFoodsRecord value4(Short value) {
        setWeight(value);
        return this;
    }

    @Override
    public EatenFoodsRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public EatenFoodsRecord values(UUID value1, UUID value2, UUID value3, Short value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EatenFoodsRecord
     */
    public EatenFoodsRecord() {
        super(EatenFoods.EATEN_FOODS_ENTITY);
    }

    /**
     * Create a detached, initialised EatenFoodsRecord
     */
    public EatenFoodsRecord(UUID id, UUID userId, UUID foodId, Short weight, LocalDateTime createdDate) {
        super(EatenFoods.EATEN_FOODS_ENTITY);

        setId(id);
        setUserId(userId);
        setFoodId(foodId);
        setWeight(weight);
        setCreatedDate(createdDate);
    }

    /**
     * Create a detached, initialised EatenFoodsRecord
     */
    public EatenFoodsRecord(EatenFoodsEntity value) {
        super(EatenFoods.EATEN_FOODS_ENTITY);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setFoodId(value.getFoodId());
            setWeight(value.getWeight());
            setCreatedDate(value.getCreatedDate());
        }
    }
}
