/*
 * This file is generated by jOOQ.
 */
package ru.itis.agona.model.jooq.schema.tables.records;


import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.itis.agona.model.jooq.schema.tables.FoodCategories;
import ru.itis.agona.model.jooq.schema.tables.pojos.FoodCategoriesEntity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoodCategoriesRecord extends UpdatableRecordImpl<FoodCategoriesRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.food_categories.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.food_categories.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.food_categories.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.food_categories.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return FoodCategories.FOOD_CATEGORIES_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return FoodCategories.FOOD_CATEGORIES_ENTITY.NAME;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public FoodCategoriesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public FoodCategoriesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public FoodCategoriesRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FoodCategoriesRecord
     */
    public FoodCategoriesRecord() {
        super(FoodCategories.FOOD_CATEGORIES_ENTITY);
    }

    /**
     * Create a detached, initialised FoodCategoriesRecord
     */
    public FoodCategoriesRecord(UUID id, String name) {
        super(FoodCategories.FOOD_CATEGORIES_ENTITY);

        setId(id);
        setName(name);
    }

    /**
     * Create a detached, initialised FoodCategoriesRecord
     */
    public FoodCategoriesRecord(FoodCategoriesEntity value) {
        super(FoodCategories.FOOD_CATEGORIES_ENTITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
        }
    }
}
