/*
 * This file is generated by jOOQ.
 */
package ru.itis.agona.model.jooq.schema;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.itis.agona.model.jooq.schema.tables.EatenFoods;
import ru.itis.agona.model.jooq.schema.tables.FavoriteDishes;
import ru.itis.agona.model.jooq.schema.tables.FoodCategories;
import ru.itis.agona.model.jooq.schema.tables.Foods;
import ru.itis.agona.model.jooq.schema.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.eaten_foods</code>.
     */
    public final EatenFoods EATEN_FOODS_ENTITY = EatenFoods.EATEN_FOODS_ENTITY;

    /**
     * The table <code>public.favorite_dishes</code>.
     */
    public final FavoriteDishes FAVORITE_DISHES_ENTITY = FavoriteDishes.FAVORITE_DISHES_ENTITY;

    /**
     * The table <code>public.food_categories</code>.
     */
    public final FoodCategories FOOD_CATEGORIES_ENTITY = FoodCategories.FOOD_CATEGORIES_ENTITY;

    /**
     * The table <code>public.foods</code>.
     */
    public final Foods FOODS_ENTITY = Foods.FOODS_ENTITY;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS_ENTITY = Users.USERS_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            EatenFoods.EATEN_FOODS_ENTITY,
            FavoriteDishes.FAVORITE_DISHES_ENTITY,
            FoodCategories.FOOD_CATEGORIES_ENTITY,
            Foods.FOODS_ENTITY,
            Users.USERS_ENTITY
        );
    }
}
