/*
 * This file is generated by jOOQ.
 */
package ru.itis.agona.model.jooq.schema;


import ru.itis.agona.model.jooq.schema.tables.EatenFoods;
import ru.itis.agona.model.jooq.schema.tables.FavoriteDishes;
import ru.itis.agona.model.jooq.schema.tables.FoodCategories;
import ru.itis.agona.model.jooq.schema.tables.Foods;
import ru.itis.agona.model.jooq.schema.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.eaten_foods</code>.
     */
    public static final EatenFoods EATEN_FOODS_ENTITY = EatenFoods.EATEN_FOODS_ENTITY;

    /**
     * The table <code>public.favorite_dishes</code>.
     */
    public static final FavoriteDishes FAVORITE_DISHES_ENTITY = FavoriteDishes.FAVORITE_DISHES_ENTITY;

    /**
     * The table <code>public.food_categories</code>.
     */
    public static final FoodCategories FOOD_CATEGORIES_ENTITY = FoodCategories.FOOD_CATEGORIES_ENTITY;

    /**
     * The table <code>public.foods</code>.
     */
    public static final Foods FOODS_ENTITY = Foods.FOODS_ENTITY;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS_ENTITY = Users.USERS_ENTITY;
}
